[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "always"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
N8N_HOST = "0.0.0.0"
N8N_PORT = "5678"
N8N_PROTOCOL = "https"